; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CMSAgent"
#define MyAppVersion "1.0.2"
#define MyAppPublisher "Your Company Name"
#define MyAppURL "https://www.yourcompany.com/"
#define MyAppExeName "agent.exe"
#define MyUpdaterExeName "updater.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
AppId={{AUTO_GUID}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf64}\CMSAgent
DefaultGroupName=CMSAgent
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=CMSAgent_Setup_{#MyAppVersion}
OutputDir=.
; Thêm icon cho file setup
SetupIconFile=icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\agent\{#MyAppExeName}

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist_agent\agent.exe"; DestDir: "{app}\agent"; Flags: ignoreversion
Source: "dist_updater\updater.exe"; DestDir: "{app}\updater"; Flags: ignoreversion
Source: "..\agent\config\agent_config.json"; DestDir: "{app}\agent\config"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\agent\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\agent\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Run agent after installation (if desired)
; Filename: "{app}\agent\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}\agent"
Type: filesandordirs; Name: "{app}\updater"
; Only delete root directory if it's empty
Type: files; Name: "{app}" 